---
  -
    id: 1
    name: "Adana"
    country_id: 1
  -
    id: 2
    name: "Adıyaman"
    country_id: 1
  -
    id: 3
    name: "Afyonkarahisar"
    country_id: 1
  -
    id: 4
    name: "Ağrı"
    country_id: 1
  -
    id: 5
    name: "Amasya"
    country_id: 1
  -
    id: 6
    name: "Ankara"
    country_id: 1
  -
    id: 7
    name: "Antalya"
    country_id: 1
  -
    id: 8
    name: "Artvin"
    country_id: 1
  -
    id: 9
    name: "Aydın"
    country_id: 1
  -
    id: 10
    name: "Balıkesir"
    country_id: 1
  -
    id: 11
    name: "Bilecik"
    country_id: 1
  -
    id: 12
    name: "Bingöl"
    country_id: 1
  -
    id: 13
    name: "Bitlis"
    country_id: 1
  -
    id: 14
    name: "Bolu"
    country_id: 1
  -
    id: 15
    name: "Burdur"
    country_id: 1
  -
    id: 16
    name: "Bursa"
    country_id: 1
  -
    id: 17
    name: "Çanakkale"
    country_id: 1
  -
    id: 18
    name: "Çankırı"
    country_id: 1
  -
    id: 19
    name: "Çorum"
    country_id: 1
  -
    id: 20
    name: "Denizli"
    country_id: 1
  -
    id: 21
    name: "Diyarbakır"
    country_id: 1
  -
    id: 22
    name: "Edirne"
    country_id: 1
  -
    id: 23
    name: "Elazığ"
    country_id: 1
  -
    id: 24
    name: "Erzincan"
    country_id: 1
  -
    id: 25
    name: "Erzurum"
    country_id: 1
  -
    id: 26
    name: "Eskişehir"
    country_id: 1
  -
    id: 27
    name: "Gaziantep"
    country_id: 1
  -
    id: 28
    name: "Giresun"
    country_id: 1
  -
    id: 29
    name: "Gümüşhane"
    country_id: 1
  -
    id: 30
    name: "Hakkari"
    country_id: 1
  -
    id: 31
    name: "Hatay"
    country_id: 1
  -
    id: 32
    name: "Isparta"
    country_id: 1
  -
    id: 33
    name: "Mersin(İçel)"
    country_id: 1
  -
    id: 34
    name: "İstanbul"
    country_id: 1
  -
    id: 35
    name: "İzmir"
    country_id: 1
  -
    id: 36
    name: "Kars"
    country_id: 1
  -
    id: 37
    name: "Kastamonu"
    country_id: 1
  -
    id: 38
    name: "Kayseri"
    country_id: 1
  -
    id: 39
    name: "Kırklareli"
    country_id: 1
  -
    id: 40
    name: "Kırşehir"
    country_id: 1
  -
    id: 41
    name: "Kocaeli"
    country_id: 1
  -
    id: 42
    name: "Konya"
    country_id: 1
  -
    id: 43
    name: "Kütahya"
    country_id: 1
  -
    id: 44
    name: "Malatya"
    country_id: 1
  -
    id: 45
    name: "Manisa"
    country_id: 1
  -
    id: 46
    name: "Kahramanmaraş"
    country_id: 1
  -
    id: 47
    name: "Mardin"
    country_id: 1
  -
    id: 48
    name: "Muğla"
    country_id: 1
  -
    id: 49
    name: "Muş"
    country_id: 1
  -
    id: 50
    name: "Nevşehir"
    country_id: 1
  -
    id: 51
    name: "Niğde"
    country_id: 1
  -
    id: 52
    name: "Ordu"
    country_id: 1
  -
    id: 53
    name: "Rize"
    country_id: 1
  -
    id: 54
    name: "Sakarya"
    country_id: 1
  -
    id: 55
    name: "Samsun"
    country_id: 1
  -
    id: 56
    name: "Siirt"
    country_id: 1
  -
    id: 57
    name: "Sinop"
    country_id: 1
  -
    id: 58
    name: "Sivas"
    country_id: 1
  -
    id: 59
    name: "Tekirdağ"
    country_id: 1
  -
    id: 60
    name: "Tokat"
    country_id: 1
  -
    id: 61
    name: "Trabzon"
    country_id: 1
  -
    id: 62
    name: "Tunceli"
    country_id: 1
  -
    id: 63
    name: "Şanlıurfa"
    country_id: 1
  -
    id: 64
    name: "Uşak"
    country_id: 1
  -
    id: 65
    name: "Van"
    country_id: 1
  -
    id: 66
    name: "Yozgat"
    country_id: 1
  -
    id: 67
    name: "Zonguldak"
    country_id: 1
  -
    id: 68
    name: "Aksaray"
    country_id: 1
  -
    id: 69
    name: "Bayburt"
    country_id: 1
  -
    id: 70
    name: "Karaman"
    country_id: 1
  -
    id: 71
    name: "Kırıkkale"
    country_id: 1
  -
    id: 72
    name: "Batman"
    country_id: 1
  -
    id: 73
    name: "Şırnak"
    country_id: 1
  -
    id: 74
    name: "Bartın"
    country_id: 1
  -
    id: 75
    name: "Ardahan"
    country_id: 1
  -
    id: 76
    name: "Iğdır"
    country_id: 1
  -
    id: 77
    name: "Yalova"
    country_id: 1
  -
    id: 78
    name: "Karabük"
    country_id: 1
  -
    id: 79
    name: "Kilis"
    country_id: 1
  -
    id: 80
    name: "Osmaniye"
    country_id: 1
  -
    id: 81
    name: "Düzce"
    country_id: 1
